# Generated by Django 5.0 on 2023-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id_produk',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
